import { z } from 'zod';
import { MATH, RACE } from '../config';
import type { Directive } from '../director/types';
import { hash, hashInt, seededStream } from '../hash';
import type { Difficulty } from '../types';
import type { GameModule, StepResult } from './types';

export interface MathQuestion {
  q: string;
  options: number[];
  answer: number;
}

export interface MathSpec {
  count: number;
  limitMs: number;
  /** The rung the block's own difficulty sits on. Where an undirected hunt stays. */
  baseRung: number;
}

export interface MathSecret {
  /** `ladder[questionIndex][rung]` — five versions of every question. */
  ladder: MathQuestion[][];
  /** Legacy shape, from blocks generated before the ladder existed. */
  questions?: MathQuestion[];
}

export interface MathState {
  index: number;
  lastServedAt: number | null;
  /**
   * The rung each question was SERVED at, recorded when it went out.
   *
   * Never recomputed at answer time. The directive that shapes a round is
   * fetched when the round is served, and a player must be judged against the
   * question they were actually shown — not against whatever the Director
   * happens to be saying by the time their answer lands.
   */
  rungs: number[];
  /** The answer window in force for the question currently on screen. */
  window: AnswerWindow;
}

export interface AnswerWindow {
  minMs: number;
  maxMs: number;
}

export interface MathInput {
  kind: string;
  value?: unknown;
}

/**
 * Five rungs of arithmetic range, one per Director difficulty.
 *
 * Rungs 1, 2 and 3 are exactly the easy/med/hard ranges this module used before
 * the Director existed, so an undirected hunt generates precisely the questions
 * it always did. The Director adds a rung below and a rung above rather than
 * moving the ground under the existing three.
 */
const LADDER = [4, 6, 12, 20, 30] as const;

/** Prize difficulty → its rung. The block's floor when nothing directs it. */
const BASE_RUNG: Record<Difficulty, number> = { easy: 1, med: 2, hard: 3 };

/**
 * Thinking time per question.
 *
 * The config's twenty seconds for three questions, restated per question so a
 * block with more of them gets proportionally longer. `MATH.maxAnswerMs` bounds
 * a single answer at eight seconds, which this comfortably clears.
 */
const MS_PER_QUESTION = MATH.limitMs / MATH.count;

/** How many questions a block may ask. */
export const MATH_COUNTS = [3, 4, 5] as const;

/**
 * The shape of one block's round.
 *
 * ─────────────────────────── why `baseRung` is NOT here ─────────────────────
 *
 * It was, briefly. `baseRung` is the arithmetic range an undirected hunt sits
 * at, and varying it per block looks like the obvious second axis — until you
 * read what rungs 1/2/3 are: the pre-Director easy/med/hard ranges, kept
 * exactly where they were measured. `math.test.ts` asserts that directly, with
 * the note that "the Director added a rung either side rather than moving the
 * ground under the three that were measured". A recipe that moved a block's
 * floor would move that ground for a different reason and leave the same test
 * with nothing to stand on.
 *
 * So the count is the axis, and it is enough to be honest about: math's CONTENT
 * already varied from the salt — no two blocks ever posed the same sums — and
 * the constant was only ever the shape of the round.
 */
export interface MathRecipe {
  count: number;
}

export const mathRecipeSchema = z
  .object({
    count: z.number().int().refine(v => (MATH_COUNTS as readonly number[]).includes(v)),
  })
  .strict();

/** The block's own round, drawn from its salt. */
export function mathRecipeFromSalt(salt: string, _difficulty: Difficulty): MathRecipe {
  return { count: MATH_COUNTS[hashInt(salt, 'math:count') % MATH_COUNTS.length]! };
}

/**
 * The question actually served for a round.
 *
 * Tolerates the pre-ladder shape: a block generated by an older build persists
 * `questions` rather than `ladder`, and its hunts are live for another hour. A
 * race that failed mid-way through because the server was redeployed under it
 * would be a worse bug than the one this compatibility costs.
 */
function questionAt(secret: MathSecret, index: number, rung: number): MathQuestion | undefined {
  const rungs = secret.ladder?.[index];
  if (!rungs) return secret.questions?.[index];
  return rungs[Math.max(0, Math.min(rungs.length - 1, rung))];
}

/**
 * How long the player gets, given the round the Director asked for.
 *
 * `roundType` and `twist` land here rather than on the arithmetic because the
 * time limit is the one knob that changes the round without changing what has
 * to be generated — and, critically, it is published: every window is sent to
 * the client with the question it applies to. A round that quietly halved
 * somebody's clock would be the Director taking a prize away, which is exactly
 * the manipulation it is blinded to prevent.
 */
export function windowFor(directive: Directive | null): AnswerWindow {
  if (!directive) return { minMs: MATH.minAnswerMs, maxMs: MATH.maxAnswerMs };

  let maxMs: number = MATH.maxAnswerMs;
  if (directive.roundType === 'sprint') maxMs = Math.round(maxMs * 0.6);
  else if (directive.roundType === 'endurance') maxMs = Math.round(maxMs * 1.5);
  if (directive.twist === 'haste') maxMs = Math.round(maxMs * 0.6);

  // `precision` buys thinking time by raising the floor rather than lowering the
  // ceiling: it asks for a considered answer, not a slower one.
  const minMs = directive.roundType === 'precision' ? MATH.minAnswerMs * 2 : MATH.minAnswerMs;

  // A hard floor the Director cannot push through however the knobs combine.
  // Reading a question and four options takes what it takes, and no directive
  // may compress the round below the point where a human can answer it at all.
  return { minMs, maxMs: Math.max(maxMs, minMs + MATH.minAnswerMs * 4) };
}

/** Directive difficulty (1–5) → ladder rung (0–4). */
const rungFor = (directive: Directive | null, spec: MathSpec): number =>
  directive ? directive.difficulty - 1 : spec.baseRung;

function makeQuestion(rnd: () => number, max: number): MathQuestion {
  const ops = ['+', '-', '×'] as const;
  const op = ops[Math.floor(rnd() * ops.length)]!;

  let a = Math.floor(rnd() * max) + 1;
  let b = Math.floor(rnd() * max) + 1;
  let answer: number;

  if (op === '+') {
    answer = a + b;
  } else if (op === '-') {
    // Keep it non-negative; subtracting into the negatives is a different skill
    // and quietly harder, which would make difficulty inconsistent between blocks.
    if (b > a) [a, b] = [b, a];
    answer = a - b;
  } else {
    const m = Math.min(9, max);
    a = Math.floor(rnd() * m) + 1;
    b = Math.floor(rnd() * m) + 1;
    answer = a * b;
  }

  const options = new Set<number>([answer]);
  let guard = 0;
  while (options.size < 4 && guard++ < 50) {
    const delta = Math.floor(rnd() * 11) - 5;
    const candidate = answer + delta;
    if (delta !== 0 && candidate >= 0) options.add(candidate);
  }
  while (options.size < 4) options.add(answer + options.size);

  const shuffled = [...options];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(rnd() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j]!, shuffled[i]!];
  }

  return { q: `${a} ${op} ${b}`, options: shuffled, answer };
}

const publicQuestion = (q: MathQuestion) => ({ q: q.q, options: q.options });

/**
 * The only one of the four where secrecy is actually available, so it is used:
 * answers stay on the server, and question N+1 is issued only once N is right.
 * That forces a real round trip per question, so the measured time contains
 * network reality rather than a batch the client precomputed.
 */
export const mathModule: GameModule<MathSpec, MathSecret, MathState, MathInput> = {
  type: 'math',

  /**
   * Every rung of every round, drawn from the block's salt in one pass.
   *
   * The whole ladder is generated up front on purpose. The Director *selects* a
   * rung, it never generates one — so the complete space of questions a hunt can
   * serve is fixed by the salt before anyone enters, and the transcript records
   * which rung was taken. Salt plus transcript still replays the exact hunt,
   * which is the property a live model must not be allowed to cost.
   */
  recipe: { schema: mathRecipeSchema, fromSalt: mathRecipeFromSalt },

  generate(seed, difficulty, ctx) {
    // Math's CONTENT already varied — `seededStream` draws a different ladder
    // from every salt, so no two blocks ever posed the same sums. What did not
    // vary was the shape of the round: three questions, twenty seconds, the
    // difficulty's rung, on every block in the game. That is why it measured at
    // one distinct spec while `crack` measured at five hundred, and it is the
    // half a recipe fixes.
    const parsed = mathRecipeSchema.safeParse(ctx?.recipe);
    const recipe = parsed.success ? parsed.data : mathRecipeFromSalt(seed, difficulty);

    const rnd = seededStream(hash(seed, 'math'));
    const ladder = Array.from({ length: recipe.count }, () =>
      LADDER.map(max => makeQuestion(rnd, max)),
    );
    // Scaled with the count rather than fixed, so a five-question block gives
    // the same thinking time per question a three-question one does. A constant
    // total would make "more questions" mean "less time each", which is a
    // different and harsher change than the one being made.
    const limitMs = Math.round(recipe.count * MS_PER_QUESTION);

    return {
      spec: { count: recipe.count, limitMs, baseRung: BASE_RUNG[difficulty] ?? 2 },
      secret: { ladder },
      limitMs,
    };
  },

  publicSpec(spec, secret) {
    // Round 0 is never directed — it goes out before the player has made any
    // progress, so there is nothing for a model to read and no directive yet
    // exists. It is always the block's own difficulty.
    const window = windowFor(null);
    return {
      count: spec.count,
      limitMs: spec.limitMs,
      index: 0,
      question: publicQuestion(questionAt(secret, 0, spec.baseRung)!),
      minAnswerMs: window.minMs,
      maxAnswerMs: window.maxMs,
    };
  },

  init(spec) {
    return {
      index: 0,
      lastServedAt: null,
      rungs: [spec.baseRung],
      window: windowFor(null),
    };
  },

  /** The round that will be served if this answer is right, if there is one. */
  directedRound(state, spec) {
    const next = state.index + 1;
    return next < spec.count ? next : null;
  },

  step({ spec, secret, state, timing, directive }, input): StepResult {
    if (timing.sinceStart > spec.limitMs + RACE.latencyGraceMs) {
      return { kind: 'reject', reason: 'too_slow', fatal: true };
    }
    if (input.kind !== 'answer') return { kind: 'reject', reason: 'bad_input', fatal: true };

    // Judged against the rung this question was SERVED at, not against whatever
    // the Director is saying now. `state.rungs` was written when the question
    // went out; a directive arriving since then shapes the next round only.
    const rung = state.rungs[state.index] ?? spec.baseRung;
    const question = questionAt(secret, state.index, rung);
    if (!question) return { kind: 'reject', reason: 'no_question', fatal: true };

    // The window the player was actually shown, for the same reason.
    const window = state.window ?? windowFor(null);
    const elapsedOnThis = state.lastServedAt === null ? timing.sinceStart : timing.sinceStart - state.lastServedAt;
    if (elapsedOnThis < window.minMs) {
      return { kind: 'reject', reason: 'answered_too_fast', fatal: true };
    }
    if (elapsedOnThis > window.maxMs) {
      return { kind: 'reject', reason: 'answered_too_slow', fatal: true };
    }

    if (typeof input.value !== 'number' || !Number.isFinite(input.value)) {
      return { kind: 'reject', reason: 'bad_answer', fatal: true };
    }
    // One wrong answer ends it — this is a race, not a quiz you can grind.
    if (input.value !== question.answer) {
      return { kind: 'reject', reason: 'wrong_answer', fatal: true };
    }

    state.index += 1;
    state.lastServedAt = timing.sinceStart;

    if (state.index >= spec.count) return { kind: 'complete' };

    // Serve the next round at whatever the Director asked for, and record both
    // choices before the question leaves — everything the next `step` judges
    // against is fixed here, at the moment the player is shown it.
    const nextRung = rungFor(directive, spec);
    const nextWindow = windowFor(directive);
    state.rungs[state.index] = nextRung;
    state.window = nextWindow;

    return {
      kind: 'progress',
      emit: {
        index: state.index,
        question: publicQuestion(questionAt(secret, state.index, nextRung)!),
        // Published, always. The player is told the clock they are racing.
        minAnswerMs: nextWindow.minMs,
        maxAnswerMs: nextWindow.maxMs,
      },
    };
  },

  progress(state, spec) {
    return Math.min(100, Math.round((state.index / spec.count) * 100));
  },
};
